### ISSUE TITLE
Exit Tickets

### ISSUE THREAD

**Issue by timfoley** [ga-dc/js1#14]
Please set aside ~5 minutes towards the end of each class to let students fill out an [Exit Ticket](http://goo.gl/forms/YQzsdpioA8) for the lesson. I'd like for exit ticket participation to be >90%. The best way to make this happen is to set a reminder for ~9:20 each night. Sending out the link while students are walking out of class doesn't work very well.

Having exit ticket data has been reallllly helpful, especially since I ask students to give their real names. If someone's struggling, this makes it much easier to reach out and help them! 

Exit ticket responses will populate directly into the [Course Tracker](https://docs.google.com/spreadsheets/d/1CH5al9OlXB8ZTIjqHGw9-e432Ks26PM4LoiejP2-Qrg/edit#gid=197139144).

**Comment by jshawl** [comment]
:+1: added link in 7c17277
