### ISSUE TITLE
EACCESS troubleshooting tutorial

### ISSUE THREAD

**Issue by timfoley** [ga-dc/js1#17]
The official curriculum encourages using http://www.wenincode.com/installing-node-jsnpm-without-sudo/ to solve the EACCESS error. Jesse's blog has a better way.

**Comment by shanazcw** [comment]
+1 -- @jshawl has an awesome solution: https://jesse.sh/sudo-npm-install/

I ran: $ sudo chown -R `whoami` /usr/local/lib/node_modules

uninstalled npm: $ sudo npm uninstall npm -g

and then after some finagling, was able to install node through the installer.
