### ISSUE TITLE
Assign Classes

### ISSUE THREAD

**Issue by jshawl** [ga-dc/js1#2]
It would be nice to decide who's teaching what for the entire course.

Options:
- choose one day of the week - consitently teach that day
- teach every other week
- draft-pick classes based on interest 

thoughts @recursivefunk

**Comment by recursivefunk** [comment]
Maybe start out with a consistent day of the week. And see how that goes? The draft-pick option sounds pretty cool too - I hear you're really into git @jshawl so I'm sure you'd deliver that better than I would!

I have no real preference on day maybe I can do Wednesdays to start out

**Comment by jshawl** [comment]
:+1: names added to calendar! always down to switch - holler if you wanna!
