### ISSUE TITLE
Lesson 4 Hubot Introduction Very Confusing

### ISSUE THREAD

**Issue by timfoley** [ga-dc/js1#23]
The introduction of Hubot at the very end of Lesson 4 left students feeling confused and in some cases frustrated. Here's an excerpt from last night's exit tickets:

> I definitely did not come out ready to start the Hubot project. It seemed like we might have run out of time toward the end. Here are a few of my questions:
> 1. How do we actually interact with the bot in Slack? (I thought I had to add it to Slack somehow, but actually it automatically becomes available once you run it locally. That's awesome but was also surprising to me.) 
> 2. The bot also has a different name in Slack than what you give it with yo, and it looks like you can link multiple bots to the same Slack name: @ga-bot-2 seemed like it was linked to three different people's pizza bots. Maybe the ./bin/hubot --name option allows you to specify your bot name for Slack? 
> 3. An example bot script in JavaScript would have been enormously helpful. 
> 4. Almost all the examples I could find online were in CoffeeScript. I initially wondered, what is CoffeeScript? What is its relationship to JavaScript? How do you convert it to JavaScript? I learned those answers after some Googling after class, but I definitely didn't feel ready by the end of class to get started on the project.

The lesson plan only brings students to the point that the bot is "live" in their terminal. The only example code it points to is a coffeescript file. At this point, they still don't know how to interact with their bot, or what sort of commands they can include in a script. The Hubot docs are very advanced for students at this point in JS. 

Given that this is introduced in the final 30 minutes of class, instead of getting students excited about Project 1, it just left them confused and a bit intimidated. At this point, I'm a bit worried about tomorrow's class. I think this lesson could be much better scaffolded, and I'm going to sit down with Jon to outline my thoughts. Expect a pull request soon :P

**Comment by JonRojas** [comment]
@timfoley - add this to the [JS Materials](https://github.com/generalassembly-studio/JS_Materials) repo!
