### ISSUE TITLE
a git class?

### ISSUE THREAD

**Issue by jshawl** [ga-dc/js1#3]
There's no class on git in the curriculum.

Teaching git early on will allow us to use github for turning in assignments and doing code reviews

recommend early on, like after installfest or right after command line js

**Comment by recursivefunk** [comment]
Absolutely. It's also a valuable skill that unfortunately gets glossed-over most of the time.

**Comment by jshawl** [comment]
:+1: will plan to teach git on day 1 after installfest!

**Comment by jshawl** [comment]
actually it looks like it's in command line js lesson - https://github.com/generalassembly-studio/JS_Materials/tree/master/curriculum/lesson-plans/01-command-line-JS

**Comment by recursivefunk** [comment]
Do we feel like it belongs there though? Seems like it would be beneficial to introduce it day 1. Then revisit during subsequent lessons. Seems a bit jarring to start with JS then take a side track with git then back to JS. Let me know if this makes sense to anyone else

**Comment by jshawl** [comment]
makes sense to me! could definitely put it right here - https://github.com/ga-dc/js1/pull/9/files#diff-8a03dde24afef1dee7fcd479b77301f9R212 gonna do it!

**Comment by recursivefunk** [comment]
Nice!

**Comment by timfoley** [comment]
Just be aware that they will not have had much (if any) experience with the command line before Install fest. Students might need some prep before they're comfortable `cd`ing into directories, etc. [Introduction to the Terminal](https://github.com/generalassembly-studio/JS_Materials/tree/master/curriculum/lesson-plans/01-command-line-JS#introduction-to-the-terminal-35-min) doesn't come until Lesson 1. 

Some students might have trouble understanding git while using unfamiliar terminal commands.

**Comment by jshawl** [comment]
I think we'll be ok! Git is hard as is. Will allow them to share their code day 1 with a formal introduction the following class
