### ISSUE TITLE
Project 1 - Slackbot

### ISSUE THREAD

**Issue by clewinth** [ga-dc/js1#30]
My hope was to be able to have the bot react to its own reaction and post a message like "did you see that?!" but I couldn't get that far.

module.exports = function (bot) {
  bot.hear(/giphy/, function(msg) {
    msg.reply('oh, puh-leeze!');

  });

  bot.hear(/exit ticket/, function(msg) {
    msg.reply('awww, do we have to?!');

  });

  bot.hear(/github/, function(msg) {
    msg.reply('@channel, he said git :-)');

  });

};

**Comment by jsm13** [comment]
Good job! I agree with the gify sentiment whole-heartedly! I don't think the responding to itself is possible or else robot.hear(/*/) with any output would cause an infinite loop which it doesn't seem to. I bet there is something in hubots code where it doesn't listen for its own messages. Very interesting idea though -- way to approach creatively!

**Comment by clewinth** [comment]
Thanks very much, John.  I’m looking forward to hopefully creating something a bit more useful next time! J
