### ISSUE TITLE
slackbot food

### ISSUE THREAD

**Issue by lapank** [ga-dc/js1#33]
I was having trouble testing within slack.  Hopefully I can catch-up with someone from the instruction team during office hours.
I have saved my JavaScript file here as a text file due to an upload error.  I'd also like to learn how other students found such cool features to use in their code to create a more complex slackbot.  

[kaylins-slackbot.txt](https://github.com/ga-dc/js1/files/194486/kaylins-slackbot.txt)

**Comment by recursivefunk** [comment]
Hey @lapank were you able to get your github issues straightened out? If not, lets tackle that asap! Good job on the documentation. Docs/comments are one of the most important parts of writing code and gets neglected far too often! You're `vegetarian`, `everything` and `paleo` variables aren't being declared with the `var` keyword. Lets make sure we use `var` for all variables in the future - great job! 👍
