### ISSUE TITLE
Tinabot

### ISSUE THREAD

**Issue by tstwine** [ga-dc/js1#34]
The purpose of my bot is when someone says- "Goodbye". The bot will reply, "I'll see you next time."

Below is the link the code is located in the script file "tina.js"
https://github.com/tstwine/mybot

**Comment by jsm13** [comment]
Nice job! A couple quick notes:
Here: https://github.com/tstwine/mybot/blob/master/scripts/tina.js#L9 you make a for-loop based on the length property of a variable called `a` which hasn't been defined (throwing an error). If instead the looping condition were based on `names` which is defined the loop would execute. Once that loop is executing, the index number `i` will be sent by the slackbot each iteration. Instead, you can use this index to access the names array and send back each name as a message.
