### ISSUE TITLE
ES6 vs ES5

### ISSUE THREAD

**Issue by recursivefunk** [ga-dc/js1#5]
ES6 is great and is becoming more relevant but in order to get it working reliably on the front end is to use a transpiler such as [babel](https://babeljs.io/) which, for beginners can really complicate the process. We can help to mitigate that by providing a boiler-plate project [such as this one](github.com/istrategylabs/mo-static) which "just works" with ES6 out of the box.

Also, ES6 in nodejs is [not yet feature complete](https://nodejs.org/en/docs/es6/). So when in the browser and using a transpiler, students would have access to all ES6 features and in nodejs they would only have access to a subset. This _could_ be confusing but it could also be a good teaching moment for creating forward-thinking constructs that _expect_ features to land (too much?).

We _could_ scratch all that and stick with ES5 but I feel like people would be missing a big piece of the puzzle

Maybe make ES6 code extra credit?

**Comment by jshawl** [comment]
:+1: Like the idea of ES6 being extra credit / bonus opportunities. Agreed sentiment on babel complicating learning process for beginners.

**Comment by recursivefunk** [comment]
Sweet.
