### ISSUE TITLE
Feedr Project - Chip Lewinthal

### ISSUE THREAD

**Issue by clewinth** [ga-dc/js1#58]
Submitting project work on which I was able to work with Jesse's, Johnny's, and Kimberly's help.
[Chip_Feedr.zip](https://github.com/ga-dc/js1/files/239592/Chip_Feedr.zip)

**Comment by jshawl** [comment]
:+1: Your code looks great!!! 

Let me know if you'd like to pair on implementing another api and choosing the news source.
