### ISSUE TITLE
Kaylin's Feedr

### ISSUE THREAD

**Issue by lapank** [ga-dc/js1#59]
Everything is working except the pop-up.

[feedr.zip](https://github.com/ga-dc/js1/files/239622/feedr.zip)

**Comment by jshawl** [comment]
⭐ Awesome job on this project!! Here's my feedback in diff form - http://www.wdidc.org/~jshawl/js1/kaylin.html

Let me know if you have any questions / would like to review together / would like specific feedback on something else!
