### ISSUE TITLE
class data management

### ISSUE THREAD

**Issue by jshawl** [ga-dc/js1#6]
in WDI, we use a rails application we built to track attendance, assignments, and student performance - http://garnet.wdidc.org/ can we use this for JS class?

**Comment by recursivefunk** [comment]
Use a rails app to manage a JS class, blasphemy! lol j/k Someone was telling me about this during the last info session sounds cool lets do it!

**Comment by jshawl** [comment]
@timfoley @recursivefunk can you click sign in w/ github and ill add you as admins?

http://garnet.wdidc.org/sign_in

Also this is rad because it means students can take their own attendance, view their status/progress in realtime and producers can export data for an audit

**Comment by recursivefunk** [comment]
Done

**Comment by timfoley** [comment]
I'm in! Really looking forward to this. This'll be my first part-time test with Garnet.

**Comment by jshawl** [comment]
:+1:
