### ISSUE TITLE
Tina's Feedr

### ISSUE THREAD

**Issue by tstwine** [ga-dc/js1#60]

**Comment by jshawl** [comment]
hey @tstwine do you have a link to your repo?

**Comment by tstwine** [comment]
Yes, I had pushed it up.through github.

**Comment by jshawl** [comment]
can you post the link to that repo here please?

**Comment by tstwine** [comment]
Here it is

https://github.com/tstwine/JS-Unit-2-Project-Starter-Code

**Comment by jshawl** [comment]
Excellent! Here's my feedback in diff form - http://www.wdidc.org/~jshawl/js1/tina.html

Let me know if you have any questions or would like to pair on implementing either another news source or getting the loading popup to show - happy to!

👍

**Comment by tstwine** [comment]
Yes, I would like to add another new source.

Thank you in advance for your assistance.
