### ISSUE TITLE
Julia's Feedr

### ISSUE THREAD

**Issue by julia-rose** [ga-dc/js1#61]
This is incomplete and SO messy and not DRY, but I'm already late so I just wanted to submit something. I'm sorry! Real life has intruded on my time.

https://github.com/julia-rose/JS-Unit-2-Project-Starter-Code

**Comment by jshawl** [comment]
Awesome job on this project! Here's my feedback in diff form - let me know if you have any questions / would like feedback on something else! http://www.wdidc.org/~jshawl/js1/julia.html

Also happy to pair on DRYing w/ a templating function
